name: imepay
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  connectivity_plus: ^6.0.4
  dio: ^5.5.0+1
  equatable: ^2.0.5
  floor: ^1.5.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.4
  get_it: ^7.7.0
  injectable: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  freezed: ^2.5.2
  build_runner: ^2.4.11
  injectable_generator: ^2.6.2
  floor_generator: ^1.5.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
